# Generated by Django 5.2.1 on 2025-05-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventparticipant",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
