# Generated by Django 5.2.1 on 2025-05-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_organizer_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('participant', 'Participant')], default='participant', max_length=20),
        ),
    ]
